name=input("Enter your name: ")
age=int(input("Enter your age: "))
course=input("Enter your course: ")
branch=input("Enter your branch: ")
print("Namae: ",name)
print("Age: "+str(age))
print(f'your cource{course}')
print("your branch: %s",branch)
print("Hello {} how can i help you".format(name))