Name=input("Enter your name: ")
age=int(input("enter your age: "))
gender=input("enter your gender: ")
deg=input("enter your degree: ")
cource=input("enter your cource: ")
print("Name: ",Name)
print(f"age: {age}")
print("gender: "+gender)
print("degree: {}\ncource: {}".format(deg,cource))